def menu():
    print("#" * 57)
    print("#            MENU                                       #")
    print("# 1 - Adicionar Compras                                 #")
    print("# 2 - Cadastrar Produto                                 #")
    print("# 3 - Listar todos os Produtos de uma determinada compra#")
    print("# 4 - Buscar Produto por ID                             #")
    print("# 5 - Excluir Produto por ID                            #")
    print("# 6 - Alterar preço                                     #")
    print("# 7 - Alterar descrição                                 #")
    print("# 8 - Buscar por descrição                              #")
    print("# 9 - Exibir listas de compra                           #")
    print("# 10 - Ver o total de determinada compra                #")
    print("# 11 - Sair                                             #")
    print("#" * 57)
